language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'
  - hhvm

install:
  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

env:
  global:
    - CC_TEST_REPORTER_ID=893a6b6bde823ce7b3739c8481b49739ae407b59c507d116a20b160925f500ef
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter -d after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
